### ISSUE TITLE
ZooKeeperNet.KeeperException+ConnectionLossException exception in ZooKeeper client 

### ISSUE THREAD

**Issue by ppekrol** [ExactTargetDev/kafka#10]
Four of our tests are failing after recent ZooKeeper Client update (https://github.com/ExactTargetDev/kafka/commit/3f60e5f81fd1f88255dd143efe712596733a352f).

We are not sure why this is happening. I've switched to the version from NuGet (http://nuget.org/packages/ZooKeeperNet/1.0.0.0) which is a version from trunk and they are passing.

Any ideas? What is the source of your version?

Here is the output from test:

DEBUG - Starting ZK client - Kafka.Client.ZooKeeperIntegration.ZooKeeperConnection
INFO  - Initiating client connection, connectstring=192.168.1.39:2181 sessionTimeout=00:00:30 watcher= - ZooKeeperNet.ZooKeeper
DEBUG - Running main send request thread loop again 0 - ZooKeeperNet.ClientConnectionRequestProducer
WARN  - Session 0x0 for server , unexpected error, closing socket connection and attempting reconnect - ZooKeeperNet.ClientConnectionRequestProducer
System.NullReferenceException: Object reference not set to an instance of an object.
   at ZooKeeperNet.ClientConnectionRequestProducer.WriteAsync()
DEBUG - Closing ZooKeeper client connected to 192.168.1.39:2181 - Kafka.Client.ZooKeeperIntegration.ZooKeeperConnection
DEBUG - Closing session: 0x0 - ZooKeeperNet.ZooKeeper
DEBUG - Closing client for session: 0x0 - ZooKeeperNet.ClientConnection
DEBUG - An exception was thrown while closing send thread for session 0x0 : Object reference not set to an instance of an object. - ZooKeeperNet.ClientConnectionRequestProducer
WARN  - Session 0x0 for server , unexpected error, closing socket connection and attempting reconnect - ZooKeeperNet.ClientConnectionRequestProducer
System.NullReferenceException: Object reference not set to an instance of an object.
   at ZooKeeperNet.ClientConnectionRequestProducer.WriteAsync()
INFO  - Opening socket connection to server 192.168.1.39:2181 - ZooKeeperNet.ClientConnectionRequestProducer
INFO  - Socket connection established to 192.168.1.39:2181, initiating session - ZooKeeperNet.ClientConnectionRequestProducer
DEBUG - Session establishment request sent on 192.168.1.39:2181 - ZooKeeperNet.ClientConnectionRequestProducer
DEBUG - Running main send request thread loop again 1 - ZooKeeperNet.ClientConnectionRequestProducer
DEBUG - Running main send request thread loop again 2 - ZooKeeperNet.ClientConnectionRequestProducer
DEBUG - Running main send request thread loop again 3 - ZooKeeperNet.ClientConnectionRequestProducer
DEBUG - Running main send request thread loop again 4 - ZooKeeperNet.ClientConnectionRequestProducer
DEBUG - Running main send request thread loop again 5 - ZooKeeperNet.ClientConnectionRequestProducer
DEBUG - Running main send request thread loop again 6 - ZooKeeperNet.ClientConnectionRequestProducer
DEBUG - Running main send request thread loop again 7 - ZooKeeperNet.ClientConnectionRequestProducer
DEBUG - Running main send request thread loop again 8 - ZooKeeperNet.ClientConnectionRequestProducer
DEBUG - Running main send request thread loop again 9 - ZooKeeperNet.ClientConnectionRequestProducer
DEBUG - Running main send request thread loop again 10 - ZooKeeperNet.ClientConnectionRequestProducer
DEBUG - Running main send request thread loop again 11 - ZooKeeperNet.ClientConnectionRequestProducer
DEBUG - Running main send request thread loop again 12 - ZooKeeperNet.ClientConnectionRequestProducer
DEBUG - Running main send request thread loop again 13 - ZooKeeperNet.ClientConnectionRequestProducer
DEBUG - Running main send request thread loop again 14 - ZooKeeperNet.ClientConnectionRequestProducer
DEBUG - Running main send request thread loop again 15 - ZooKeeperNet.ClientConnectionRequestProducer
DEBUG - Running main send request thread loop again 16 - ZooKeeperNet.ClientConnectionRequestProducer
DEBUG - Running main send request thread loop again 17 - ZooKeeperNet.ClientConnectionRequestProducer
DEBUG - Running main send request thread loop again 18 - ZooKeeperNet.ClientConnectionRequestProducer
DEBUG - SendThread exitedloop. - ZooKeeperNet.ClientConnectionRequestProducer
INFO  - EventThread shut down - ZooKeeperNet.ClientConnectionEventConsumer
INFO  - Session: 0x0 closed - ZooKeeperNet.ZooKeeper
DEBUG - ZooKeeper client connection closed - Kafka.Client.ZooKeeperIntegration.ZooKeeperConnection

ZooKeeperNet.KeeperException+ConnectionLossException : Exception of type 'ZooKeeperNet.KeeperException+ConnectionLossException' was thrown.
at ZooKeeperNet.ZooKeeper.Create(String path, Byte[] data, List`1 acl, CreateMode createMode)
at Kafka.Client.ZooKeeperIntegration.ZooKeeperConnection.Create(String path, Byte[] data, CreateMode mode) in ZooKeeperConnection.cs: line 179
at Kafka.Client.IntegrationTests.ZooKeeperConnectionTests.ZooKeeperConnectionWritesAndReadsData() in ZooKeeperConnectionTests.cs: line 107

**Comment by ewhauser** [comment]
I believe we have this issue fixed in the latest version of ZookeeperNet.  Torrey is fixing a problem with connection retries right now, and that is the only known issue.
