### ISSUE TITLE
Increasing the number of consumers with the same group id causes duplicated consumed messages

### ISSUE THREAD

**Issue by tteats** [ExactTargetDev/kafka#11]
I have a test case that produces approximately 10K messages a minute and consumers that come online every 20 seconds for 3 minutes on a Kafka setup with one node and 10 partitions.  Upon the completion of the test, approximately 10% of the messages produced were duplicated when consuming. It looks like the offsets that the new consumers start with are getting the offsets that are outdated, which causes these duplicates.  This is the simplest form of the test. In reality we will have consumers coming on and off line so we need to have consumers that do not duplicate this many messages.

**Comment by tteats** [comment]
I have investigated further and see that the FetchedDataCollection appears to get the same offsets added more than once when you keep adding consumers.  A place to look is the ZookeeperConsumerConnector.Consume method.  The ZK watcher must be adding the same data chunk more than once.  I have logs from my test and logs from Kafka/Zookeeper. I will need to email them though.

**Comment by bosman** [comment]
I've finally managed to fix this issue. Please retest just to be sure. I have also reverted the zookeepernet.dll to the previous one. The one introduced recently broke a few of the tests. We have no idea where it came from as the one that we used to use before was the most recent one (see https://github.com/ExactTargetDev/kafka/issues/10).

**Comment by tteats** [comment]
I did try my tests against and things are certainly better with regards to replaying when consumers are added. However, using several consumers when a producer is still way ahead can pretty easily yield duplicates. Plus, I notice that only a small portion of the threads I have using new consumers are actually doing any work.  Is this expected? It looks like a consumer picks a partition and sticks with it.  Many times the producer is sticking to one partition on the writes. I don't know if that's how it is supposed to work or not.  Note that if I have several producers logging errors they do logged to different partitions.

Also, by rolling back the ZK dll I notice that the unprotected exception in the timeout logic there now will cause the whole application to crash. That is what the fix was supposed to fix.  I will work with Casey about trying to get your failing test cases working.

**Comment by tteats** [comment]
Fixed now.
