### ISSUE TITLE
Client needs to support queuedchunks.max property for consumer

### ISSUE THREAD

**Issue by tteats** [ExactTargetDev/kafka#16]
Documentation: http://incubator.apache.org/kafka/configuration.html

One of our consumers is not very fast about pulling items off, which is causing the Fetcher to get more and more messages queued but just sit in memory, eventually causing out of memory exceptions. Can you please support this setting so we can govern how many queued chunks to maintain?

**Comment by bosman** [comment]
Support added along with some unit/integration tests. I was unsure about one thing - the default value. In the documentation (link in the original ticket note) the default is 100 but in the scala/java code the default is set to 10. I decided to use 10 as well. Please let me know if I should change that to 100 instead.

**Comment by tteats** [comment]
10 works for me. Memory is much more under control now.
