### ISSUE TITLE
OOM error

### ISSUE THREAD

**Issue by ewhauser** [ExactTargetDev/kafka#2]
Occasional OOME due to what looks like a corrupt message size (580,425,244) on the wire.  Could be related to #1 ?   Line 223 Kafka.Client.Messages.BufferedMessageSet.

**Comment by jmckinleyET** [comment]
If it helps, I can confirm that the message size coming through on the wire matches what the client code is calculating it as - in other words, it looks like the client is not mangling the message. It may be looking in the wrong place, though (just a guess, not based on anything).

**Comment by jmckinleyET** [comment]
Looking at the raw Kafka log file (on the server), the offset that was being requested is in the middle of a message, and the data at that offset matches the invalid message size my program is receiving - so, the kafka client is parsing the text of a message as a size.

**Comment by bosman** [comment]
Fixed. Please rerun tests on your side to confirm and close the ticket.

**Comment by ewhauser** [comment]
This is a duplicate of #4
