### ISSUE TITLE
Stopping a consumer while there are lots of messages simultaneously getting published and then restarting results in error

### ISSUE THREAD

**Issue by tteats** [ExactTargetDev/kafka#5]
Stopping a consumer while there are lots of messages simultaneously getting published and then restarting, causes this error:

Invalid message size. Read size = 896, the remaining data size = 502
2012-04-30 16:20:20,947 [16] ERROR Kafka.Client.Messages.BufferedMessageSet [(null),(null),(null)] - Invalid message size. Read size = 896, the remaining data size = 502   ExactTarget.Core.Logging.StackTraceConverter.Convert line 0  ExactTarget.Diagnostics.EtErrorAppender.Append line 0  Kafka.Client.Messages.BufferedMessageSet.ParseFrom line 0  Kafka.Client.Messages.BufferedMessageSet.ParseMultiFrom line 0  Kafka.Client.Consumers.Consumer.MultiFetch line 0  Kafka.Client.Consumers.FetcherRunnable.Run line 0  System.Threading.ExecutionContext.runTryCode line 0  System.Runtime.CompilerServices.RuntimeHelpers.ExecuteCodeWithGuaranteedCleanup line 0  System.Threading.ExecutionContext.Run line 0  System.Threading.ExecutionContext.Run line 0  System.Threading.ThreadHelper.ThreadStart line 0  

I am publishing around 50K messages of varying sizes a minute for this test.

**Comment by bosman** [comment]
There were two commits lately. The first one was still bugged but the second one solved this problem, at least for me and jmckinleyET. I spent lots of time trying to do something to reproduce this after that commit but couldn't. Are the messages you send compressed or uncompressed? Does this happen in both cases? How large are they? What is your consumer configuration?

**Comment by tteats** [comment]
The message is an Avro message with compression set to CompressionCodecs.NoCompressionCodec.  I will try to turn on compression to see if anything changes.  The byte size varies but is around 109 bytes.  

```
    <kafkaConsumer groupId="group1" timeout="-1">
      <zookeeper>
        <servers>
          <add host="in3722.local" port="2181" />
        </servers>
      </zookeeper>
    </kafkaConsumer>
```

I can repro it every time with the test I have but it integrates with a lot of specific stuff I'm working on.  I am trying to use your integration unit tests to see if I can repro but have not been able to.  The only thing I was able to find was the issue where committing the offsets was not happening on dispose.  As I find more information, I will update.

**Comment by tteats** [comment]
I have more information on this problem.  It has to do with the the MaxFetchSize in the FetchRequest.  When the backlog is huge, then it is easy to fill up the whole max batch size. It appears the client always assumes that the message will fit perfectly within that batch size.  Perhaps some error checking would be handy to set the offset accordingly on the next fetch to Kafka.  Here is a unit test that shows the problem.  The test never finishes because it gets stuck. However, look at the log4net kafka logs to see the error above.  Put a breakpoint where the error happens and you see that the buffer size isn't guaranteed to be a valid length here.

``` csharp
public void MaxFetchSizeBug()
        {
            var prodConfig = this.SyncProducerConfig1;
            var consumerConfig = this.ZooKeeperBasedConsumerConfig;
            consumerConfig.FetchSize = 256;
            consumerConfig.NumberOfTries = 1;
            consumerConfig.AutoCommitInterval = 1000;
            int numberOfMessagesToSend = 100;
            string topic = CurrentTestTopic;

            var msgList = new List<Message>();
            using (var producer = new SyncProducer(prodConfig))
            {
                for (int i = 0; i < numberOfMessagesToSend; i++)
                {
                    string payload = CreatePayloadByNumber(i+100);
                    byte[] payloadData = Encoding.UTF8.GetBytes(payload);
                    var msg = new Message(payloadData);
                    msgList.Add(msg);
                    var producerRequest = new ProducerRequest(topic, 0, new List<Message>() {msg});
                    producer.Send(producerRequest);
                }
            }

            // now consuming
            int messageNumberCounter = 0;
            using (IConsumerConnector consumerConnector = new ZookeeperConsumerConnector(consumerConfig, true))
            {
                var topicCount = new Dictionary<string, int> { { topic, 1 } };
                var messages = consumerConnector.CreateMessageStreams(topicCount);
                var sets = messages[topic];

                try
                {
                    foreach (var set in sets)
                    {
                        foreach (var message in set)
                        {
                            Assert.AreEqual(CreatePayloadByNumber(messageNumberCounter+100), Encoding.UTF8.GetString(message.Payload));
                            messageNumberCounter++;
                        }
                    }
                }
                catch (ConsumerTimeoutException)
                {
                    // do nothing, this is expected
                }
            }

            Assert.AreEqual(numberOfMessagesToSend, messageNumberCounter);
        }
```

**Comment by tteats** [comment]
Notice from above me setting the FetchSize property to something small. This makes it quick and easy to repro.

**Comment by bosman** [comment]
You were right. I reproduced this with the test code above and fixed. The code is committed.
